name: Auto Merge develop to develop-humble

on:
  workflow_call:
    inputs:
      branch_from:
        required: true
        type: string
      branch_to:
        required: true
        type: string
      notify_team:
        required: false
        type: string
        default: "DevOps"

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "SaikrishnaBairamoni"
          git config user.email "saikrishna.bairamoni@leidos.com"
          git fetch --all

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr list --base ${{ inputs.branch_to }} --head ${{ inputs.branch_from }} --json number --jq '.[0].number')
          
          if [ -z "$pr_number" ]; then
            echo "No existing PR found. Creating a new PR"
            pr_number=$(gh pr create \
              --title "Merge ${{ inputs.branch_from }} into ${{ inputs.branch_to }}" \
              --body "Automated PR to merge ${{ inputs.branch_from }} into ${{ inputs.branch_to }}" \
              --base ${{ inputs.branch_to }} \
              --head ${{ inputs.branch_from }} \
              --json number --jq '.number')
          fi

          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV

      - name: Attempt to Auto-Merge Pull Request
        if: ${{ env.PR_NUMBER != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ env.PR_NUMBER }} --merge --admin || exit 1

      - name: Notify Team on Conflict
        if: ${{ failure() && inputs.notify_team != '' && env.PR_NUMBER != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ env.PR_NUMBER }} --body "@${{ inputs.notify_team }}: Conflicts detected. Manual resolution needed."
